### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by shouxd** [TerraformersMC/Campanion#88] opened 2020-10-19 03:41 UTC
Whenever I place a tent and look at it memory goes up to 100%, game begins to stutter and stays like that until I pick up the tent and then restart the game. Its worth to note that I have to pick up the tent otherwise if I restart and look at it again, the problem persists.

**Comment by NeusFear** [comment] 2020-10-19 03:49
Duplicate of #53 ?

**Comment by shouxd** [comment] 2020-10-19 07:03
Yes, sems like. Happened to me while using Sodium too

**Comment by NeusFear** [comment] 2020-10-27 16:29
dupicate of #53

**Closed as completed by NeusFear** 2020-10-27 16:29 UTC
Labels: duplicate
