### ISSUE TITLE
two things but great mod otherwise

### ISSUE THREAD

**Issue by Worgrick** [TerraformersMC/Campanion#24] opened 2020-05-04 03:10 UTC
Spears loyalty enchant does not work; second I can not place unmade tents, or put them in a tent bag

**Comment by NeusFear** [comment] 2020-05-04 03:13
As for loyalty; it isnt intended to "work" spears are meant to be an early game version of the trident, not a cheaper replacement, so we decided to omit that one.

I don't really understand what you mean by the inability to place unmade tents, could you elaborate?

**Comment by Worgrick** [comment] 2020-05-04 08:59
First you craft the tent check
Second place nope, or put in bag nope.
But listen man I can give a wood sword all the same enchantments as a diamond sword, no exceptions. Not only does it make sense it also is not late game. If I'm using diamonds I want that tool to come back to me other wise, they need to stack or something because they're main functionality is in thier projectile quality. I would use a diamond shovel for melees, because it is less intense on resources, while doing more damage.

**Comment by Worgrick** [comment] 2020-05-04 09:01
I'm working on A mod pack for the nether update now. It's just something that play around with on my own but still.

**Comment by NeusFear** [comment] 2020-05-10 20:42
I am thinking about some of these changes and I think what I want to do instead is just make the spears do a little more damage and maybe reach further. We're not going to add the loyalty enchant probably still though.

**Comment by NeusFear** [comment] 2020-05-10 20:44
I can't reproduce your tent bag issues so I'm just going to assume they were fixed in a later version

**Comment by NeusFear** [comment] 2020-05-10 20:46
moved updated suggestion to #26

**Closed as completed by NeusFear** 2020-05-10 20:46 UTC
Labels: enhancement
