### ISSUE TITLE
Crashing after trying to use a Hiking Pack

### ISSUE THREAD

**Issue by RealMelodyHope** [TerraformersMC/Campanion#152] opened 2021-10-27 05:16 UTC
Hi.
Playing with the 2.0 beta, and I encountered a weird thing.
I tried opening up a Hiking Pack while in creative mode... and I crashed.
Now it causes me to crash every time I open up my inventory, even in survival mode.
What should I do?

**Comment by RealMelodyHope** [comment] 2021-10-27 05:16
The game crashed whilst rendering entity in world
Error: java.lang.ClassCastException: class com.terraformersmc.campanion.item.BackpackItem cannot be cast to class net.minecraft.class_1738 (com.terraformersmc.campanion.item.BackpackItem and net.minecraft.class_1738 are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @141e5bef)
Exit Code: -1

This is what came up ^

**Comment by jhbuchanan45** [comment] 2021-11-08 12:53
Incompatibility with Wildfire's Female Gender Mod. Since the mod is closed source as best as I can tell, I'm leaving the ball in their court to fix the issue, I don't have time to guess what their mod is doing.

@RealMelodyHope Could you close this issue since we found the cause? Thanks!

**Closed as completed** 2021-11-08 13:45 UTC
